version: "3.1"
services:
  db:
    image: mongo:latest
    ports:
      - 27017:27017
  api:
    build:
      context: .
    environment:
      MONGODB_URI: mongodb://db:27017/template-service
      TZ: America/Tegucigalpa
      LC_CTYPE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      AWS_KEYID: AKIAY62NM6GGW7YNOEXE
      AWS_KEYSECRET: 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
      JWT_SECRET: P455W0RD
      AWS_WELCOME_EMAIL_ACCOUNT: emanuelesausosa@gmail.com
    ports:
      - 3000:3000
