version: "3.1"
services:
  db:
    image: mongo:latest
    ports:
      - 27019:27017
  api:
    build:
      context: .
    environment:
      MONGODB_URI: mongodb://db:27017/onlinestore-service
      TZ: America/Tegucigalpa
      LC_CTYPE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      AWS_KEYID: AKIAY62NM6GGW7YNOEXE
      AWS_KEYSECRET: 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
      JWT_SECRET: P455W0RD
      AWS_WELCOME_EMAIL_ACCOUNT: emanuelesausosa@gmail.com
      PORT: 3004
    ports:
      - 3004:3000
