swagger:
  outputDirectory: ./dist
  entryFile:
    - ./src/domains/**/controllers/*
  outputFormat: OpenApi_3
  name: Customer-Service API
  description: This a Rest API for Customer-Service
  license: MIT
  produces: [application/json]
  version: 0.0.1
  securityDefinitions:
    default:
      type: apiKey
      in: header
      name: Authorization
    secondAuthenticator:
      type: apiKey
      in: header
      name: Authorization
